// @ts-check
import { defineConfig } from 'astro/config';

// Screenshots are generated by `npm run screenshots` (and by the
// "Refresh tool data" workflow), not during the build.
// https://astro.build/config
export default defineConfig({
    vite: {
        css: {
            transformer: "lightningcss",
            lightningcss: {
                drafts: {
                    customMedia: true,
                },
            },
        },
    },
});
