name: Deploy via FTP

on:
  push:
    branches:
      - prod
  workflow_run:
    workflows: ["Check tool status"]
    branches:
      - prod
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: prod

      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: v2202511242415400947.hotsrv.de
          username: dmxmicrosite
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: /home/users/dmxmicrosite/www/tools.hsbi-gestaltung.de/


